language: go

env:
  matrix:
    - BUILD_GOOS=linux BUILD_GOARCH=amd64 BUILD_NAME=amd64
    - BUILD_GOOS=linux BUILD_GOARCH=arm BUILD_GOARM=6 BUILD_NAME=armv6
    - BUILD_GOOS=linux BUILD_GOARCH=arm BUILD_GOARM=7 BUILD_NAME=armv7
    - BUILD_GOOS=linux BUILD_GOARCH=arm64 BUILD_NAME=aarch64
    - BUILD_GOOS=freebsd BUILD_GOARCH=amd64 BUILD_NAME=amd64
    - BUILD_GOOS=freebsd BUILD_GOARCH=arm BUILD_GOARM=6 BUILD_NAME=armv6
    - BUILD_GOOS=freebsd BUILD_GOARCH=arm BUILD_GOARM=7 BUILD_NAME=armv7
    - BUILD_GOOS=freebsd BUILD_GOARCH=arm64 BUILD_NAME=aarch64

script:
  - go test -v ./...
  - mkdir dist
  - GOOS=$BUILD_GOOS GOARCH=$BUILD_GOARCH GOARM=$BUILD_GOARM go build -v ./... -o dist/callmonster-$BUILD_GOOS-$BUILD_NAME
